Day07_MVC/Day07_MVC/Models/ErrorViewModel.cs
using System;

namespace Day07_MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Day07_MVC/Day07_MVC/Models/HangHoa.cs
using System.ComponentModel.DataAnnotations;

namespace Day07_MVC.Models
{
    public class HangHoa
    {
        [Display(Name ="Mã số")]
        public int MaHh { get; set; }

        [Display(Name = "Tên hàng hóa")]
        public string TenHh{ get; set; }
        [Display(Name = "Hình")]
        public string Hinh{ get; set; }

        [Display(Name = "Đơn giá")]
        public double DonGia{ get; set; }
        [Display(Name = "Số lượng")]
        public int SoLuong{ get; set; }
        [Display(Name = "Thành tiền")]
        public double ThanhTien => DonGia * SoLuong;
    }
}

Day07_MVC/Day07_MVC/Models/SinhVien.cs
using System.ComponentModel.DataAnnotations;

namespace Day07_MVC.Models
{
    public class SinhVien
    {
        [Display(Name ="Mã SV")]
        public int MaSV { get; set; }
        [Display(Name ="Họ tên")]
        public string HoTen { get; set; }
        [Display(Name ="Điểm")]
        public double Diem { get; set; }
        [Display(Name = "Xếp loại")]
        public string XepLoai
        {
            get
            {
                if (Diem < 5) return "Yếu";
                if (Diem < 7) return "Trung bình";
                if (Diem < 8.5) return "Khá";
                return "Giỏi";
            }
        }
    }
}

Day07_MVC/Day07_MVC/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Day07_MVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace Day07_MVC.Controllers
{
    public class DemoController : Controller
    {
        public IActionResult Index()
        {
            ViewBag.DiaChi = "105 Bà Huyện Thanh Quan";
            ViewBag.HoTen = "Nhất Nghệ";
            ViewData["DienThoai"] = 3928102365;
            ViewData["Ngay Sinh"] = new DateTime(2000, 11, 21);

            var hangHoa = new HangHoa
            {
                MaHh = 1, 
                TenHh = "Iphone 12 256Gb Gold",
                DonGia = 29990000,
                SoLuong = 3
            };
            ViewBag.DienThoai = hangHoa;

            return View();
        }

        public IActionResult DanhSach()
        {
            var data = new List<HangHoa>();
            data.Add(new HangHoa
            {
                MaHh = 1, TenHh = "Iphone 12",
                DonGia = 2999000, SoLuong = 3,
                Hinh = "iphone12.png"
            });
            data.Add(new HangHoa
            {
                MaHh = 2, TenHh = "IPad 2020",
                DonGia = 1399000, SoLuong = 7,
                Hinh = "ipad-8-wifi-32gb-2020.png"
            });

            return View(data);
        }

        public IActionResult ChiTiet()
        {
            var hangHoa = new HangHoa
            {
                MaHh = 2,
                TenHh = "IPad 2020",
                DonGia = 1399000,
                SoLuong = 7,
                Hinh = "ipad-8-wifi-32gb-2020.png"
            };

            return View(hangHoa);
        }

        public IActionResult ThemHangHoa()
        {
            return View();
        }
    }
}

Day07_MVC/Day07_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Day07_MVC.Models;

namespace Day07_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Day07_MVC/Day07_MVC/Controllers/SinhVienController.cs
using Day07_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.IO;

namespace Day07_MVC.Controllers
{
    public class SinhVienController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private string fileText = "datasv.txt";
        private string fileJson = "datasv.json";

        [HttpPost]
        public IActionResult Manage(SinhVien sv, string GhiFile)
        {
            if (GhiFile == "Ghi file JSON")
            {
                var jsonSv = JsonConvert.SerializeObject(sv);
                var fullPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "JsonData", fileJson);

                System.IO.File.WriteAllText(fullPath, jsonSv);
                var desktopUrl = @"C:\Users\NN\Desktop\aaa.json";
                System.IO.File.WriteAllText(desktopUrl, jsonSv);
            }
            else
            {
                //ghi file text
                var data = new string[]
                {
                    sv.MaSV.ToString(),
                    sv.HoTen,
                    sv.Diem.ToString()
                };
                var fullPathText = Path.Combine(Directory.GetCurrentDirectory(), "Data", fileText);

                System.IO.File.WriteAllLines(fullPathText, data);
            }
            return View("Index");
        }

        public IActionResult DocJson()
        {
            var fullPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "JsonData", fileJson);
            var content = System.IO.File.ReadAllText(fullPath);

            var sv = JsonConvert.DeserializeObject<SinhVien>(content);

            return View("Index", sv);
        }
    }
}

Day07_MVC/Day07_MVC/Views/SinhVien/Index.cshtml
@model Day07_MVC.Models.SinhVien

@{
    ViewData["Title"] = "Index";
}

<h3>Thông tin Sinh Viên</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Manage" asp-controller="SinhVien">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaSV" class="control-label"></label>
                <input asp-for="MaSV" class="form-control" />
                <span asp-validation-for="MaSV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoTen" class="control-label"></label>
                <input asp-for="HoTen" class="form-control" />
                <span asp-validation-for="HoTen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Diem" class="control-label"></label>
                <input asp-for="Diem" class="form-control" />
                <span asp-validation-for="Diem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="XepLoai" class="control-label"></label>
                <input asp-for="XepLoai" class="form-control" />
                <span asp-validation-for="XepLoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" name="GhiFile" value="Ghi file Text" class="btn btn-primary" />
                <input type="submit" name="GhiFile" value="Ghi file JSON" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>